### ISSUE TITLE
RLGlue is returning a 2D observation array, rl_glue_ale_agent expects 3D

### ISSUE THREAD

**Issue by coventry** [spragunr/deep_q_rl#15]
The agent fails on [this line](https://github.com/spragunr/deep_q_rl/blob/master/deep_q_rl/rl_glue_ale_agent.py#L274):

```python
image = observation[128:].reshape(IMAGE_HEIGHT, IMAGE_WIDTH, 3)
```

because `observation[128:]` has only `IMAGE_HEIGHT*IMAGE_WIDTH` values in my hands.

This is with `rl-glue_3.04-1_amd64.deb`, and ALE git commit [`ee826630d1`](https://github.com/mgbellemare/Arcade-Learning-Environment/commit/ee826630d12d28926ed2ccea7802c824c5350830).  I'm running with the command

```bash
python ale_run.py --exp_pref data -r breakout.bin --display
```

**Comment by alito** [comment]
Easier to track this if you post to the list. If I had to guess, it'd be that you have a different 'ale' binary that is being found that is older.

**Comment by coventry** [comment]
Thank you, that was the issue.
