### ISSUE TITLE
Choose action with epsilon set to self.epsilon instead of 1.0 prior to hitting replay size

### ISSUE THREAD

**Issue by alito** [spragunr/deep_q_rl#22]
Before the agent has seen replay_start_size frames, it collects frames while acting randomly (epsilon hardcoded to 1.0). Changing this to choose_action with epsilon at self.epsilon would help with resuming runs, since you could set the epsilon_start to some number approximately equal to what it was when the run got interrupted, and replay_start_size to a million, and it would be very close to being a smooth resume. When starting a new run, self.epsilon would be 1.0 anyway so nothing would change.

The one-line patch explains it better and more succinctly:
<pre><code>
--- a/deep_q_rl/rl_glue_ale_agent.py
+++ b/deep_q_rl/rl_glue_ale_agent.py
@@ -571,7 +571,7 @@ class NeuralAgent(Agent):
                 self.loss_averages.append(loss)
         else:
             # save the data and pick one at random since we haven't hit the replay size
-            int_action, considered = self.choose_action(self.data_set, 1.0,
+            int_action, considered = self.choose_action(self.data_set, self.epsilon,
                                  current_image, np.clip(reward, -1, 1))
 
         # Map it back to ALE's actions
</code></pre>

**Comment by alito** [comment]
hmmm... that patch was from my branch, which uses slightly different signature. I made a pull request from a clean branch instead. #23

**Comment by spragunr** [comment]
PR #23 merged.
