### ISSUE TITLE
Memory error, sysmalloc: Assertion failed

### ISSUE THREAD

**Issue by temporonni** [spragunr/deep_q_rl#29]
Hi there,
The previous version of you code using `RL-Glue` is working good for me, but when I try to get the new version up and running I receive the following error:

```
> ./run_nips.py --rom breakout
Using gpu device 0: GeForce GTX 770
A.L.E: Arcade Learning Environment (version 0.5.0)
[Powered by Stella]
Use -help for help screen.
Warning: couldn't load settings file: ./stellarc
Game console created:
  ROM file:  ../../../roms/breakout.bin
  Cart Name: Breakout - Breakaway IV (1978) (Atari)
  Cart MD5:  f34f08e5eb96e500e851a80be3277a56
  Display Format:  AUTO-DETECT ==> NTSC
  ROM Size:        2048
  Bankswitch Type: AUTO-DETECT ==> 2K

Running ROM file...
Random Seed: 123
INFO:root:OPENING breakout_07-21-16-20_0p0002_0p95/results.csv
INFO:root:training epoch: 1 steps_left: 50000
python: malloc.c:2372: sysmalloc: Assertion `(old_top == (((mbinptr) (((char *) &((av)->bins[((1) - 1) *
2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) 
>= (unsigned long)((((__builtin_offsetof (struct malloc_chunk, fd_nextsize))+((2 *(sizeof(size_t))) - 
1)) & ~((2 *(sizeof(size_t))) - 1))) && ((old_top)->size & 0x1) && ((unsigned long) old_end & 
pagemask) == 0)' failed.
Aborted (core dumped)
```

Just wondering if anyone knows the cause/fix to this problem. Thanks in advance

**Comment by spragunr** [comment]
Sorry... I haven't seen this issue, and I'm not sure what would cause it.  Make sure that Theano is updated to the latest version.  You could also try clearing the Theano cache by deleting the .theano directory. How much memory do you have on your machine?

**Comment by moscow25** [comment]
I'd like to confirm that clearing Theano cache worked for me, in a
previous, but related issue (with RL_GLUE version).

theano-cache purge

And as for device memory, there's also a known issue (or maybe fixed now)
in Theano, where if you're using over 50% of memory on a machine before
booting up CUDA, it can cause a memory fail, despite having plenty of
device memory left.
https://github.com/Theano/Theano/issues/2184

The point is, clear the cache, and monitor memory usage. If you're able to
request a spot instance 8x GPU on AWS, that can be helpful. They sure are
expensive, though...

Best,
N

**Comment by livenletdie** [comment]
How did you debug the above issue? I am getting the same error when running in caffe.
