### ISSUE TITLE
ROM file wont load

### ISSUE THREAD

**Issue by arccoxx** [spragunr/deep_q_rl#30]
Hi,

I just set up the library and ran the install_dependencies.sh file. Unfortunatley when I put in the command /home/aidan/Desktop/deep_q_rl-master/deep_q_rl/run_nips.py --rom Breakout.bin into terminal in ubuntu I get:

 A.L.E: Arcade Learning Environment (version 0.5.0)
[Powered by Stella]
Use -help for help screen.
Warning: couldn't load settings file: ./stellarc
No ROM File specified or the ROM file was not found.

Any thoughts on how to fix this?

**Comment by spragunr** [comment]
Have you downloaded the ROM file? ROMS need to be obtained separately. E.g.:

https://atariage.com/2600/roms/Breakout.zip

**Comment by arccoxx** [comment]
Whoah thanks for the speedy response!

I downloaded the file and added it to the roms directory. I have tried running the file as both a .bin and .zip. Perhaps it has something to do with the fact that it cant find the stellarc file?

**Comment by mcmachado** [comment]
This is related to the ALE. You should try to rename your ROM to breakout.bin. The ROM should be on the lowercase. The ALE expects a specific filename containing each of the ROMs.

**Comment by arccoxx** [comment]
The file is now named: "breakout.bin". But still it's giving me the same error.

**Comment by mcmachado** [comment]
It doesn't look like an ALE error then. The issue with ROMs have been addressed in this post: https://groups.google.com/forum/#!topic/arcade-learning-environment/1IL4dnLSpfo

I don't want to state the obvious, but did you check if the code is properly receiving this parameter? And if the obvious thing is if the file is where you are defining it.

I responded here because I thought it could be an ALE error, but it seems it is not.

**Comment by moscow25** [comment]
You can also test the ROM by downloading Stella separately, on your laptop,
etc. That will tell you whether the ROM is good.

Intuitively, I agree that most likely error is it not looking for the right
file, somewhere in code. I'd grep for it...

Best,
N

On Thu, Jul 30, 2015 at 1:18 PM, Marlos C. Machado <notifications@github.com

**Comment by arccoxx** [comment]
groovy thanks

**Comment by spragunr** [comment]
The code is configured to expect the ROM file to be stored in the existing folder named "roms".  The default location is configurable in the executable scripts.

**Comment by stone8oy** [comment]
well, you just need to copy the file " stellarc"  ( listed in last :
https://github.com/stone8oy/deep_q_rl/tree/master/deep_q_rl ) to that
directory,

2015-07-31 1:57 GMT+08:00 Nathan Sprague <notifications@github.com>:

**Comment by spragunr** [comment]
No word on this for a while, and no one else has reported a problem.  I'm closing the issue.

**Comment by citihome** [comment]
I had configured the environment according the instructions, also, I had download the ROM, but when I execute the scripts run_nature.py, in line 203 (of launcher.py) ale.loadROM(full_rom_path), the console shows me the message "It seems the kernel died unexpectedly, use 'restart kernel' to continue using this console"
what should I do then?

**Comment by citihome** [comment]
Hi,
there is something wrong with lasagne package when execute the scripts run_nature.py
we get the following information by config dnn/cuda mode
I wannder how to fix the problem

hutch@hutch-ubuntu:/media/hutch/D26CCB6F6CCB4CC3/workspace/python/dl/build$ python run_nature.py --rom breakout
A.L.E: Arcade Learning Environment (version 0.5.0)
[Powered by Stella]
Use -help for help screen.
Warning: couldn't load settings file: ./stellarc
Game console created:
  ROM file:  ../roms/breakout.bin
  Cart Name: Breakout - Breakaway IV (1978) (Atari)
  Cart MD5:  f34f08e5eb96e500e851a80be3277a56
  Display Format:  AUTO-DETECT ==> NTSC
  ROM Size:        2048
  Bankswitch Type: AUTO-DETECT ==> 2K

Running ROM file...
Random Seed: 65
Traceback (most recent call last):
  File "run_nature.py", line 66, in <module>
    launcher.launch(sys.argv[1:], Defaults, __doc__)
  File "/media/hutch/D26CCB6F6CCB4CC3/workspace/python/dl/build/launcher.py", line 223, in launch
    rng)
  File "/media/hutch/D26CCB6F6CCB4CC3/workspace/python/dl/build/q_network.py", line 53, in __init__
    num_actions, num_frames, batch_size)
  File "/media/hutch/D26CCB6F6CCB4CC3/workspace/python/dl/build/q_network.py", line 161, in build_network
    batch_size)
  File "/media/hutch/D26CCB6F6CCB4CC3/workspace/python/dl/build/q_network.py", line 290, in build_nature_network_dnn
    from lasagne.layers import dnn
  File "/usr/local/anaconda/lib/python2.7/site-packages/lasagne/layers/dnn.py", line 13, in <module>
    raise ImportError("dnn not available")  # pragma: no cover
ImportError: dnn not available
hutch@hutch-ubuntu:/media/hutch/D26CCB6F6CCB4CC3/workspace/python/dl/build$ python run_nature.py --rom breakout
A.L.E: Arcade Learning Environment (version 0.5.0)
[Powered by Stella]
Use -help for help screen.
Warning: couldn't load settings file: ./stellarc
Game console created:
  ROM file:  ../roms/breakout.bin
  Cart Name: Breakout - Breakaway IV (1978) (Atari)
  Cart MD5:  f34f08e5eb96e500e851a80be3277a56
  Display Format:  AUTO-DETECT ==> NTSC
  ROM Size:        2048
  Bankswitch Type: AUTO-DETECT ==> 2K

Running ROM file...
Random Seed: 65
Traceback (most recent call last):
  File "run_nature.py", line 66, in <module>
    launcher.launch(sys.argv[1:], Defaults, __doc__)
  File "/media/hutch/D26CCB6F6CCB4CC3/workspace/python/dl/build/launcher.py", line 223, in launch
    rng)
  File "/media/hutch/D26CCB6F6CCB4CC3/workspace/python/dl/build/q_network.py", line 53, in __init__
    num_actions, num_frames, batch_size)
  File "/media/hutch/D26CCB6F6CCB4CC3/workspace/python/dl/build/q_network.py", line 157, in build_network
    output_dim, num_frames, batch_size)
  File "/media/hutch/D26CCB6F6CCB4CC3/workspace/python/dl/build/q_network.py", line 227, in build_nature_network
    from lasagne.layers import cuda_convnet
  File "/usr/local/anaconda/lib/python2.7/site-packages/lasagne/layers/cuda_convnet.py", line 30, in <module>
    raise ImportError("requires a GPU to work")  # pragma: no cover
ImportError: requires a GPU to work

**Comment by citynorman** [comment]
Here's what I did:
1) download https://atariage.com/2600/roms/Breakout.zip and extract to deep_q_rl/roms
2A) run deep_q_rl/deep_q_rl/run_nips.py --rom Breakout (ie upper case)
2B) rename Breakout.bin to breakout.bin (lower case) and run  deep_q_rl/deep_q_rl/run_nips.py --rom breakout

Be good to add those steps to dep_script.sh
