### ISSUE TITLE
Reproducibility

### ISSUE THREAD

**Issue by Ivanopolo** [spragunr/deep_q_rl#33]
Current implementation does not support reproducibility which might be useful for research purposes. I already implemented it and tested (get 100% reproducible results). If it's of interest, please, let me know, I can do a PR.

**Comment by spragunr** [comment]
That would be a nice feature, as long as it doesn't add too much complexity to the code.  If it involves big changes, I probably won't have time to evaluate and test in the near future.

**Comment by jleni** [comment]
Hi Ivano,
In the meantime, could you make a branch in your own fork and post it?
I would like to see the differences.
Thanks!

**Comment by Ivanopolo** [comment]
Sure, I have a local one, but it has too many changes. I'll make a clean one this weekend.

**Comment by spragunr** [comment]
Addressed by PR#37.
