### ISSUE TITLE
Training results don't match Deepmind implementation

### ISSUE THREAD

**Issue by spragunr** [spragunr/deep_q_rl#34]
In principle, there should be no significant algorithmic differences between this implementation and the Deepmind code.  This code was developed to be consistent with the description from Nature paper.  Where the paper was ambiguous, I've looked into their torch/lua code for clarification.  All of the default parameters are set to match those described in the Nature paper. 

For some unknown reason(s) the learning dynamics for this implementation *don't* match the reference lua implementation.  In general, the current code seems to learn well for a while, then the quality of the policy drops off with continued training.

**Comment by Ivanopolo** [comment]
How bad is it? I mean, did you have a chance to test different games? What's the difference in terms of rewards per epoch? Results of deep_q_rl can't match paper results or even DQN tests that you run locally?
I haven't run full 200-epoch tests on the initial algorithm assuming that it would be identical to the paper. Yet with my implementation there were also issues with convergence after some 35-50 epochs.
Additionally, are there any ideas what could be wrong? What tests should we do in order to find the bug? What can I do to help? I mean there is no other Theano implementation of DQN that I'm aware of, so we have to make this one work. I'm currently researching the possibilities to improve DQN algorithm and it's hard exaggerate the importance of being able to match the published results. :)

**Comment by mcmachado** [comment]
But we don't really know the shape of their curves, right? I mean, when they report their results they use the best agent along all the epochs, so the story could still be consistent, they learn until a certain point and they use that agent, regardless of all the rest... Also, notice that recent papers report DQN results and they present two columns: (1) their obtained results with DQN and (2) the results reported in Nature.

**Comment by spragunr** [comment]
@Ivanopolo   This thead on the mailing list has some work on quantifying the difference in rewards/epoch on Breakout.  I haven't tried other games with the latest version of the code.

https://groups.google.com/d/msg/deep-q-learning/K2zo-9I5pM8/fthhQqF7GgAJ

I agree that matching the performance from the Nature paper is important.  Unfortunately, I don't know of an easy way to find the bug.  Some ideas:

* Write code for loading saved weights from the torch implementation into Theano, then test with those weights.  This would help confirm that the testing code, preprocessing etc. are consistent. 
*   Perform identical initialization of all weights in both deep_q_rl and the Deepmind code (all set to .1 or something), then perform a weight update with identical inputs. The inputs could be synthetic, it wouldn't be necessary to try to get matching game screens.  Instrument both implementations to print intermediate values from the weight updates.
* Someone with time on their hands good take a good systematic look at both implementations.  I've spent some time on this, but someone with fresh eyes might catch a difference.

**Comment by spragunr** [comment]
@mcmachado We can get a look at the curves by running the Deepmind Torch code. The way that implementation reports results seems to be consistent with the way we are reporting results.  They store the best agent across all epochs, but rewards are printed for each epoch.  Follow the link here to see the differences on Breakout:

https://groups.google.com/d/msg/deep-q-learning/K2zo-9I5pM8/fthhQqF7GgAJ

**Comment by peterzcc** [comment]
Any updates about this strange bug? Hope we could find the reason as soon as possible..

**Comment by davidsj** [comment]
#46 probably explains some of this discrepancy.

**Comment by spragunr** [comment]
It looks like issue #46  was the culprit here.  The issue is addressed in PR #47.  Thanks @davidsj  for the fix.
